-- CHOIMEETSCHEDULE.MEETYN(CHAR 'Y'/'N') → MEETST(TINYINT 1=선택 2=취소 3=만남) 이전.
-- 기존 데이터가 있는 운영 DB에서만 수동 실행. (신규 DB는 mysql-init/01_schema.sql 이 이미 MEETST 로 생성함)
-- 실행: mysql -u choi3 -p choi3 < migrations/2026-09-13_meetst.sql

USE choi3;

ALTER TABLE CHOIMEETSCHEDULE ADD COLUMN MEETST TINYINT NOT NULL DEFAULT 1 AFTER MEETYN;

UPDATE CHOIMEETSCHEDULE
SET MEETST = CASE
  WHEN MEETYN = 'Y' THEN 3
  WHEN CANCELRS IS NOT NULL AND CANCELRS <> '' THEN 2
  ELSE 1
END;

ALTER TABLE CHOIMEETSCHEDULE DROP COLUMN MEETYN;
