-- 체크 항목을 요일별로 완전히 분리 — 요일마다 별도의 항목 목록을 관리자가 각각 관리한다
-- (기존엔 항목 하나를 모든 요일이 공유했음). 요일마다 기본 5개 빈 항목을 시드로 넣는다.
-- 이전 마이그레이션(2026-09-21_choichecklist_v2.sql)의 테이블을 대체한다 — 아직 운영 미반영 +
-- 로컬 테스트 데이터뿐이라 안전하게 DROP 후 재생성.
-- 운영 DB 적용: mysql -u choi3 -p choi3 < migrations/2026-09-22_choichecklist_v3.sql

USE choi3;

DROP TABLE IF EXISTS CHOICHECKLIST_HISTORY;
DROP TABLE IF EXISTS CHOICHECKLIST;
DROP TABLE IF EXISTS CHOICHECKLIST_ITEM;
DROP TABLE IF EXISTS CHOICHECKLIST_STAMP;

-- 요일별 체크 항목 — DOW 1=월 ... 7=일. 관리자가 요일마다 각각 추가/수정/삭제.
CREATE TABLE CHOICHECKLIST_ITEM (
    ID         INT          NOT NULL AUTO_INCREMENT,
    DOW        TINYINT      NOT NULL,
    LABEL      VARCHAR(50)  NOT NULL DEFAULT '',
    SORT_ORDER INT          NOT NULL DEFAULT 0,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 이번 주(마감 전) 체크 상태 — 항목이 이미 요일을 갖고 있어 DOW 컬럼이 필요 없다.
CREATE TABLE CHOICHECKLIST (
    NTT_ID  INT      NOT NULL,
    ITEM_ID INT      NOT NULL,
    CHECKED CHAR(1)  NOT NULL DEFAULT 'N',
    MOD_DT  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (NTT_ID, ITEM_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 이번 주 요일별 스탬프 — 해당 요일 전 항목이 체크된 사용자에게 관리자가 부여.
CREATE TABLE CHOICHECKLIST_STAMP (
    NTT_ID INT      NOT NULL,
    DOW    TINYINT  NOT NULL,
    REG_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (NTT_ID, DOW)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 주 마감 시 남기는 요일별 요약 이력.
CREATE TABLE CHOICHECKLIST_HISTORY (
    NTT_ID        INT      NOT NULL,
    WEEK_START    DATE     NOT NULL,
    DOW           TINYINT  NOT NULL,
    CHECKED_COUNT INT      NOT NULL,
    TOTAL_COUNT   INT      NOT NULL,
    STAMPED       CHAR(1)  NOT NULL DEFAULT 'N',
    PRIMARY KEY (NTT_ID, WEEK_START, DOW)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 체크리스트 공개 페이지 관리자 비밀번호(단일 행) — 기존 값 보존을 위해 DROP하지 않는다.
CREATE TABLE IF NOT EXISTS CHOICHECKLIST_ADMIN (
    ID       TINYINT      NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO CHOICHECKLIST_ADMIN (ID, PASSWORD) VALUES (1, 'CHECK_KEY');

-- 요일마다 기본 5개 빈 항목 시드(라벨은 관리자가 채워 넣는다).
INSERT INTO CHOICHECKLIST_ITEM (DOW, LABEL, SORT_ORDER)
SELECT d.dow, '', s.seq FROM
  (SELECT 1 AS dow UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7) d
  CROSS JOIN
  (SELECT 1 AS seq UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) s;
